apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: train-detection

resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: quay.io/username/train-detection-streamlit
    newName: quay.io/mouachan/train-detection-streamlit
    newTag: latest
